javascript:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc
  linter:
    rules:
      no-console: off
      indent: [error, 2, { SwitchCase: 1 }]
      max-len: [error, { code: 100 }]
      space-before-function-paren: [error, always]
      linebreak-style: [error, unix]
      brace-style: [error, 1tbs, { allowSingleLine: true }]
      no-trailing-spaces: error
      space-before-blocks: error
      keyword-spacing: [error, { before: true, after: true }]
      space-infix-ops: error
      no-unneeded-ternary: error
      comma-spacing: [error, { before: false, after: true }]
      semi: [error, always]
      quotes: [error, single, { avoidEscape: true }]
      no-var: error
      prefer-const: error
      eqeqeq: [error, always]
      no-unused-vars: [error, { args: none }]
      no-multiple-empty-lines: [error, { max: 1, maxEOF: 0 }]
      eol-last: [error, always]
